export const ADD_ARTICLE = 'ADD_ARTICLE';
export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const SEARCH_ARTICLE = 'SEARCH_ARTICLE';
export const SORT_ARTICLES = 'SORT_ARTICLES';
export const SEARCH_BY_CATEGORY = 'SEARCH_BY_CATEGORY';
export const RESET_ARTICLE_DATA = 'RESET_ARTICLE_DATA';
export const LOAD_HOMEPAGE_ARTICLES = 'LOAD_HOMEPAGE_ARTICLES';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
